name: release

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - run: ls
      - name: Get Project Version
        id: getversion
        run: ./gradlew getVersionFromJava
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/gregtech-${{ steps.getversion.outputs.version }}.jar
