name: release

on: 
  workflow_dispatch:
    branches: [ test ]
    inputs:
      releaseTag:
        description: 'Release Tag'
        required: true
        default: 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Get Project Version
        id: getversion
        run: echo ::set-output name=version::$(./gradlew getVersionFromJava --q)
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.releaseTag }}
          files: build/libs/gregtech-${{ steps.getversion.outputs.version }}.jar
